// ColorConstants.ets

export enum ColorConstants {
  TAB_SELECTED = '#007AFF',
  TAB_UNSELECTED = '#9E9E9E',
  NAVIGATION_BG_COLOR='#9E9E9E',//'#FFFFFF',
  TABS_BG_COLOR='#F44336',
    HOME_PAGE_BG_COLOR='#F5F5F5',//'#F5F5F5',
    HOME_PAGE_TITLE_BG_COLOR='#FFE4E1',




  PRIMARY_BLUE = '#2196F3',    // Material Blue 500
  IOS_BLUE = '#007AFF',        // iOS 高亮蓝
  DODGER_BLUE = '#1E90FF',     // 鲜亮蓝
  TAILWIND_BLUE = '#3B82F6',   // Tailwind Blue 500

  WHITE = '#FFFFFF',
  BLACK = '#000000',
  LIGHT_GRAY = '#F5F5F5',
  GRAY = '#9E9E9E',
  DARK_GRAY = '#424242',

  SUCCESS_GREEN = '#4CAF50',
  WARNING_YELLOW = '#FF9800',
  ERROR_RED = '#F44336',

  ALERT_RED = '#FF0000',
}
